jenkins:
  ports:
  - 18080:8080/tcp
  hostname: jenkins
  image: jenkins:latest
  links:
  - wlpcluster01:wlpcluster01
  - chefserver:chefserver
  volumes:
  - /home/devops/rancher/server/jenkins_home:/var/jenkins_home
wlpcluster01:
  environment:
    LICENSE: accept
    appnamelist: SWIS
    clustermember1: wlpcluster02
    clustermember2: wlpcluster03
    ctrlhostname: wlpcluster01
    role: master
  entrypoint:
  - bash
  - -c
  - /usr/sbin/sshd;su -p wasadmin -c "bash /wlpconfig/controller.sh";sleep 240;su -p wasadmin -c "bash /wlpconfig/failover.sh"; sleep 10;su -p wasadmin -c "bash /wlpconfig/wlpcluster_bootstrap.sh"
  hostname: wlpcluster01
  image: wlpserver_chefclient:centos7
  links:
  - wlpcluster02:wlpcluster02
  - wlpcluster03:wlpcluster03
  - chefserver:chefserver
  volumes:
  - /home/devops/rancher/server/chefserver/shared_data/etc_client:/etc/chef
chefserver:
  ports:
  - 443:443/tcp
  entrypoint:
  - bash
  - -c
  - /usr/sbin/sshd & /opt/opscode/embedded/bin/runsvdir-start & /opt/chef-manage/embedded/bin/runsvdir-start
  hostname: chefserver
  image: chefserver12_chefmanage_sshd:ubuntu
  privileged: true
  volumes:
  - /home/devops/rancher/server/chefserver/etc_opscode:/etc/opscode
  - /home/devops/rancher/server/chefserver/etc_chef_manage:/etc/chef-manage
  - /home/devops/rancher/server/chefserver/var_log_opscode:/var/log/opscode
  - /home/devops/rancher/server/chefserver/var_log_chef_manage:/var/log/chef-manage
  - /home/devops/rancher/server/chefserver/var_opt_opscode:/var/opt/opscode
  - /home/devops/rancher/server/chefserver/var_opt_chef_manage:/var/opt/chef-manage
  - /home/devops/rancher/server/chefserver/shared_data:/data
wlpcluster02:
  environment:
    LICENSE: accept
    appnamelist: SWIS
    clustermember1: wlpcluster02
    clustermember2: wlpcluster03
    ctrlhostname: wlpcluster01
    role: member
  entrypoint:
  - bash
  - -c
  - /usr/sbin/sshd;sleep 180;su -p wasadmin -c "bash /wlpconfig/controller.sh";su -p wasadmin -c "bash /wlpconfig/wlpcluster_bootstrap.sh"
  hostname: wlpcluster02
  image: wlpserver_chefclient:centos7
wlpcluster03:
  environment:
    LICENSE: accept
    appnamelist: SWIS
    clustermember1: wlpcluster02
    clustermember2: wlpcluster03
    ctrlhostname: wlpcluster01
    role: member
  entrypoint:
  - bash
  - -c
  - /usr/sbin/sshd;sleep 210;su -p wasadmin -c "bash /wlpconfig/controller.sh";su -p wasadmin -c "bash /wlpconfig/wlpcluster_bootstrap.sh"
  hostname: wlpcluster03
  image: wlpserver_chefclient:centos7
